# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllHostelMetaData',
            fields=[
                ('hostelName', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hostelCode', models.CharField(max_length=255, unique=True)),
                ('hostelGensec', models.CharField(max_length=255)),
                ('hostelCTid', models.CharField(max_length=255, unique=True)),
                ('hostelRoom', models.CharField(max_length=255, unique=True)),
                ('hostelRoomOccupant', models.CharField(max_length=255, unique=True)),
                ('hostelViewPermission', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AllHostelMetaData',
                'verbose_name_plural': 'AllHostelMetaData',
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('roomNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('roomOccupancyType', models.CharField(max_length=255)),
                ('floorInfo', models.CharField(max_length=255)),
                ('roomStatus', models.CharField(max_length=255)),
                ('roomOccupancyGender', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'HostelRoom',
                'verbose_name_plural': 'HostelRoom',
            },
        ),
        migrations.CreateModel(
            name='HostelRoomOccupantRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(max_length=255)),
                ('roomNo', models.CharField(max_length=255)),
                ('occupantId', models.CharField(max_length=255)),
                ('messStatus', models.CharField(max_length=255)),
                ('toMess', models.DateField()),
                ('fromMess', models.DateField()),
                ('toRoomStay', models.DateField()),
                ('fromRoomStay', models.DateField()),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'HostelRoomOccupantRelation',
                'verbose_name_plural': 'HostelRoomOccupantRelation',
            },
        ),
        migrations.CreateModel(
            name='HostelViewAccess',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('webmail', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HostelViewAccess',
                'verbose_name_plural': 'HostelViewAccess',
            },
        ),
        migrations.CreateModel(
            name='OccupantCategory',
            fields=[
                ('occupantId', models.IntegerField()),
                ('abbrevation', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OccupantCategory',
                'verbose_name_plural': 'OccupantCategory',
            },
        ),
        migrations.CreateModel(
            name='OccupantDetails',
            fields=[
                ('idType', models.CharField(max_length=255)),
                ('idNo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('saORda', models.CharField(max_length=255)),
                ('webmail', models.CharField(max_length=255)),
                ('altEmail', models.CharField(max_length=255)),
                ('mobNo', models.CharField(max_length=255)),
                ('emgercencyNo', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics')),
                ('bankAccount', models.CharField(max_length=255)),
                ('IFSCCode', models.CharField(max_length=255)),
                ('accHolderName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OccupantDetails',
                'verbose_name_plural': 'OccupantDetails',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('roomId', models.IntegerField()),
                ('abbrevation', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'RoomCategory',
                'verbose_name_plural': 'RoomCategory',
            },
        ),
        migrations.CreateModel(
            name='barakRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'barakRoom',
                'verbose_name_plural': 'barakRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='barakRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'barakRORelation',
                'verbose_name_plural': 'barakRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='barakView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'barakView',
                'verbose_name_plural': 'barakView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='bramhaputraRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'bramhaputraRoom',
                'verbose_name_plural': 'bramhaputraRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='bramhaputraRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'bramhaputraRORelation',
                'verbose_name_plural': 'bramhaputraRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='bramhaputraView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'bramhaputraView',
                'verbose_name_plural': 'bramhaputraView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='dhansiriRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'dhansiriRoom',
                'verbose_name_plural': 'dhansiriRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='dhansiriRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'dhansiriRORelation',
                'verbose_name_plural': 'dhansiriRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='dhansiriView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'dhansiriView',
                'verbose_name_plural': 'dhansiriView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='dibangRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'dibangRoom',
                'verbose_name_plural': 'dibangRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='dibangRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'dibangRORelation',
                'verbose_name_plural': 'dibangRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='dibangView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'dibangView',
                'verbose_name_plural': 'dibangView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='dihingRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'dihingRoom',
                'verbose_name_plural': 'dihingRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='dihingRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'dihingRORelation',
                'verbose_name_plural': 'dihingRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='dihingView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'dihingView',
                'verbose_name_plural': 'dihingView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='kamengRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'kamengRoom',
                'verbose_name_plural': 'kamengRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='kamengRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'kamengView',
                'verbose_name_plural': 'kamengView',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='kamengView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'kamengView',
                'verbose_name_plural': 'kamengView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='kapiliRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'kapiliRoom',
                'verbose_name_plural': 'kapiliRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='kapiliRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'kapiliRORelation',
                'verbose_name_plural': 'kapiliRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='kapiliView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'kapiliView',
                'verbose_name_plural': 'kapiliView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='lohitRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'lohitRoom',
                'verbose_name_plural': 'lohitRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='lohitRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'lohitRORelation',
                'verbose_name_plural': 'lohitRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='lohitView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'lohitView',
                'verbose_name_plural': 'lohitView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='manasRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'manasRoom',
                'verbose_name_plural': 'manasRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='manasRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'manasRORelation',
                'verbose_name_plural': 'manasRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='manasView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'manasView',
                'verbose_name_plural': 'manasView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='siangRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'siangRoom',
                'verbose_name_plural': 'siangRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='siangRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'siangRORelation',
                'verbose_name_plural': 'siangRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='siangView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'siangView',
                'verbose_name_plural': 'siangView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='subansiriRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'subansiriRoom',
                'verbose_name_plural': 'subansiriRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='subansiriRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'subansiriRORelation',
                'verbose_name_plural': 'subansiriRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='subansiriView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'subansiriView',
                'verbose_name_plural': 'subansiriView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
        migrations.CreateModel(
            name='umiamRoom',
            fields=[
                ('hostelroom_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoom')),
            ],
            options={
                'verbose_name': 'umiamRoom',
                'verbose_name_plural': 'umiamRoom',
            },
            bases=('hab_app.hostelroom',),
        ),
        migrations.CreateModel(
            name='umiamRORelation',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'umiamRORelation',
                'verbose_name_plural': 'umiamRORelation',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
        migrations.CreateModel(
            name='umiamView',
            fields=[
                ('hostelviewaccess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelViewAccess')),
            ],
            options={
                'verbose_name': 'umiamView',
                'verbose_name_plural': 'umiamView',
            },
            bases=('hab_app.hostelviewaccess',),
        ),
    ]
