# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupantdetails',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
