# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupantdetails',
            name='emgercencyNo',
            field=models.CharField(max_length=255),
        ),
    ]
