# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0002_occupantdetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Table',
            fields=[
                ('hostelroomoccupantrelation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hab_app.HostelRoomOccupantRelation')),
            ],
            options={
                'verbose_name': 'Log_Table',
                'verbose_name_plural': 'Log_Table',
            },
            bases=('hab_app.hostelroomoccupantrelation',),
        ),
    ]
