# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0003_log_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingOccupant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupantName', models.CharField(max_length=255)),
                ('occupantIdCategory', models.CharField(max_length=255)),
                ('occupantId', models.CharField(max_length=255)),
                ('hostelName', models.CharField(max_length=255)),
                ('roomNo', models.CharField(blank=True, max_length=255, null=True)),
                ('fromStay', models.DateField()),
                ('toStay', models.DateField()),
            ],
            options={
                'verbose_name': 'UpcomingOccupant',
                'verbose_name_plural': 'UpcomingOccupant',
            },
        ),
    ]
