# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0004_upcomingoccupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingoccupant',
            name='occupantIdCategory',
        ),
        migrations.AddField(
            model_name='upcomingoccupant',
            name='idType',
            field=models.CharField(choices=[('Rollno', 'Rollno'), ('Project Id', 'Project Id'), ('GovtId_VoterCard', 'GovtId_VoterCard'), ('GovtID_AadharCard', 'GovtID_AadharCard'), ('GovtIDPassportNo', 'GovtIDPassportNo')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingoccupant',
            name='hostelName',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam')], max_length=255),
        ),
    ]
