# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0005_auto_20171007_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allhostelmetadata',
            name='hostelName',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam')], max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='roomOccupancyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hab_app.RoomCategory'),
        ),
        migrations.AlterField(
            model_name='occupantdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='occupantdetails',
            name='idType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hab_app.OccupantCategory'),
        ),
        migrations.AlterField(
            model_name='occupantdetails',
            name='saORda',
            field=models.CharField(choices=[('Specially/Differently Abled', 'Specially/Differently Abled'), ('No', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupant',
            name='idType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hab_app.OccupantCategory'),
        ),
    ]
