# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0006_auto_20171021_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupantdetails',
            name='idType',
            field=models.CharField(choices=[('Rollno', 'Rollno'), ('Project Id', 'Project Id'), ('GovtId_VoterCard', 'GovtId_VoterCard'), ('GovtID_AadharCard', 'GovtID_AadharCard'), ('GovtIDPassportNo', 'GovtIDPassportNo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupant',
            name='idType',
            field=models.CharField(choices=[('Rollno', 'Rollno'), ('Project Id', 'Project Id'), ('GovtId_VoterCard', 'GovtId_VoterCard'), ('GovtID_AadharCard', 'GovtID_AadharCard'), ('GovtIDPassportNo', 'GovtIDPassportNo')], max_length=255),
        ),
    ]
