# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0007_auto_20171021_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('webmail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingOccupantRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestname', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('Rollno', 'Rollno'), ('Project Id', 'Project Id'), ('GovtId_VoterCard', 'GovtId_VoterCard'), ('GovtID_AadharCard', 'GovtID_AadharCard'), ('GovtIDPassportNo', 'GovtIDPassportNo')], max_length=255)),
                ('id_no', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('Address', models.CharField(max_length=300)),
                ('Pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('Mobile_No', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Emergency_Mobile_No', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Webmail_id', models.CharField(max_length=255)),
                ('Alternate_email_id', models.EmailField(max_length=254)),
                ('Bank_Name', models.CharField(max_length=255)),
                ('Account_Holder_Name', models.CharField(max_length=255)),
                ('Bank_Account_No', models.IntegerField()),
                ('IFSCCode', models.CharField(max_length=255)),
                ('From_Date', models.DateField()),
                ('To_Date', models.DateField()),
                ('Purpose_Of_Stay', models.CharField(choices=[('Intern', 'Intern'), ('Project', 'Project'), ('Unofficial', 'Unofficial')], max_length=255)),
                ('Host_Name', models.CharField(max_length=255)),
                ('Host_Webmail_Id', models.CharField(max_length=255)),
                ('Host_Id', models.PositiveIntegerField()),
                ('To_be_approved_by', models.CharField(choices=[('HOD_CSE', 'HOD_CSE'), ('HOSAA', 'HOSAA'), ('chr_hab', 'chr_hab')], max_length=255)),
                ('isApprovedFirst', models.BooleanField(default=False)),
                ('isApprovedChr', models.BooleanField(default=False)),
                ('Preference_Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hab_app.RoomCategory')),
            ],
            options={
                'verbose_name': 'allotment',
                'verbose_name_plural': 'allotment',
            },
        ),
    ]
