# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0008_login_upcomingoccupantrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upcomingoccupantrequest',
            unique_together=set([('Mobile_No', 'Emergency_Mobile_No')]),
        ),
    ]
