# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0009_auto_20171021_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='isApprovedChr',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='isApprovedFirst',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=255),
        ),
    ]
