# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0010_auto_20171022_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingoccupantrequest',
            name='hostelName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='To_be_approved_by',
            field=models.CharField(choices=[('hodcse', 'hodcse'), ('HOSAA', 'HOSAA'), ('chr_hab', 'chr_hab')], max_length=255),
        ),
    ]
