# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0011_auto_20171108_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupantdetails',
            name='bankName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupantdetails',
            name='idPhoto',
            field=models.ImageField(blank=True, upload_to='id_pics'),
        ),
        migrations.AlterField(
            model_name='hostelroomoccupantrelation',
            name='messStatus',
            field=models.CharField(choices=[('Subscribed', 'Subscribed'), ('Unsubscribed', 'Unsubscribed'), ('PayAndEat', 'PayAndEat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='Host_Id',
            field=models.CharField(max_length=255),
        ),
    ]
