# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 23:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0012_auto_20171108_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupantdetails',
            name='Address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupantdetails',
            name='Pincode',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
    ]
