# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0013_auto_20171108_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroomoccupantrelation',
            name='fromMess',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomoccupantrelation',
            name='toMess',
            field=models.DateField(blank=True, null=True),
        ),
    ]
