# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0014_auto_20171108_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='floorInfo',
            field=models.CharField(choices=[('Ground', 'Ground'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='roomOccupancyGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='roomStatus',
            field=models.CharField(choices=[('Usable', 'Usable'), ('Abandoned', 'Abandoned'), ('Partially Damaged', 'Partially Damaged')], max_length=255),
        ),
    ]
