# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0015_auto_20171109_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='roomOccupancyGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='occupantdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='upcomingoccupantrequest',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255),
        ),
    ]
