# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0017_auto_20171201_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='floorInfo',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Seconf Floor', 'Seconf Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='roomOccupancyGender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
