# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hab_app', '0018_auto_20171201_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='floorInfo',
            field=models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor')], max_length=255),
        ),
    ]
