# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='catering',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='cleanliness',
            field=models.CharField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='hostelName',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_b',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_d',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='qual_l',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='hostelName',
            field=models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam')], max_length=255),
        ),
    ]
