# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='cleanliness',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Neutral'), (5, 'Good'), (6, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='preference',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preference',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
