# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_auto_20171223_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
