# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_auto_20171223_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opi_calculated',
            unique_together=set([('hostelName', 'month'), ('hostelName', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('username', 'year'), ('username', 'month')]),
        ),
    ]
