# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0008_auto_20171224_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='month_year',
            field=models.CharField(default='11_2017', max_length=255),
        ),
        migrations.AlterField(
            model_name='preference',
            name='month_year',
            field=models.CharField(default='1_2018', max_length=255),
        ),
    ]
