# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0009_auto_20171224_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='opi_calculated',
            name='month_year',
            field=models.CharField(default='11_2017', max_length=255),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='opi_calculated',
            name='year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterUniqueTogether(
            name='messfeedback',
            unique_together=set([('username', 'month_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='opi_calculated',
            unique_together=set([('hostelName', 'month_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('username', 'month_year')]),
        ),
    ]
